[package]
name = "data-studio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"

gtk4 = "0.4.8"
#gtk = { version = "0.4.8", package = "gtk4" }